More German
collective/plone.app.locales pull request #380
Opened 2022-11-07 23:47 UTC by DravenTheRaven

I've added some of the missing German translations

2022-11-08 00:16 UTC, Arhell approved these changes

2022-11-08 08:31 UTC, jensens requested changes
Ein Haufen Tippfehler, einige Begriffkonsistenzprobleme und bestimmste Dinge, die nicht übersetzt werden sollen, da sonst kein Mensch weiss, was das soll.

2022-11-08 08:31 UTC, jensens commented on plone/app/locales/locales/de/LC_MESSAGES/plone.po
> +msgstr "Entweder die Quelle oder das Ziel exisiert nicht mehr "
```suggestion
msgstr "Entweder die Quelle oder das Ziel existiert nicht mehr"
```

2022-11-08 08:31 UTC, jensens commented on plone/app/locales/locales/de/LC_MESSAGES/plone.po
> +msgstr "Filterregeln"
```suggestion
msgstr "Filterregeln:"
```

2022-11-08 08:31 UTC, jensens commented on plone/app/locales/locales/de/LC_MESSAGES/plone.po
> +msgstr "Globales Debug-Modus aktiviert"
```suggestion
msgstr "Globaler Debug-Modus aktiviert"
```

2022-11-08 08:31 UTC, jensens commented on plone/app/locales/locales/de/LC_MESSAGES/plone.po
> +msgstr "Zu Ihrer Seite gehen"
```suggestion
msgstr "Zurück zu Ihrer Webseite."
```

2022-11-08 08:31 UTC, jensens commented on plone/app/locales/locales/de/LC_MESSAGES/plone.po
> +msgstr "Zu Upgradeseite gehen"
```suggestion
msgstr "Zur Upgrade-Seite gehen"
```

2022-11-08 08:31 UTC, jensens commented on plone/app/locales/locales/de/LC_MESSAGES/plone.po
> +msgstr "Ausblenden"
```suggestion
msgstr "Verstecken"
```

2022-11-08 08:31 UTC, jensens commented on plone/app/locales/locales/de/LC_MESSAGES/plone.po
> +msgstr "Infos"
```suggestion
msgstr "Information:"
```

2022-11-08 08:31 UTC, jensens commented on plone/app/locales/locales/de/LC_MESSAGES/plone.po
> +msgstr "Der Name darf nicht leer sein"
```suggestion
msgstr "Der Name darf nicht leer sein."
```

2022-11-08 08:31 UTC, jensens commented on plone/app/locales/locales/de/LC_MESSAGES/plone.po
> +msgstr "Datensatz ${name} exisiert schon"
```suggestion
msgstr "Datensatz ${name} existiert schon."
```

2022-11-08 08:31 UTC, jensens commented on plone/app/locales/locales/de/LC_MESSAGES/plone.po
> +msgstr "Datensatz ${name} erstellt"
```suggestion
msgstr "Datensatz ${name} erstellt."
```

2022-11-08 08:31 UTC, jensens commented on plone/app/locales/locales/de/LC_MESSAGES/plone.po
> +msgstr "Datensatz gelöcht"
```suggestion
msgstr "Datensatz gelöscht."
```

2022-11-08 08:31 UTC, jensens commented on plone/app/locales/locales/de/LC_MESSAGES/plone.po
> +msgstr "Ressourcen-Debugmodus aktiveirt"
```suggestion
msgstr "Debug-Modus für Ressourcen ist aktiviert"
```

2022-11-08 08:31 UTC, jensens commented on plone/app/locales/locales/de/LC_MESSAGES/plone.po
> +msgstr "Ressourcenkataster"
```suggestion
msgstr "Ressourcen-Registrierung"
```
(keep it as is in 5.2)

2022-11-08 08:31 UTC, jensens commented on plone/app/locales/locales/de/LC_MESSAGES/plone.po
> +msgstr "Server"
```suggestion
msgstr "Server:"
```

2022-11-08 08:31 UTC, jensens commented on plone/app/locales/locales/de/LC_MESSAGES/plone.po
> +msgstr "Kennwort festlegen"
```suggestion
msgstr "Passwort festlegen"
```
(es ist überall Passwort)

2022-11-08 08:31 UTC, jensens commented on plone/app/locales/locales/de/LC_MESSAGES/plone.po
> +msgstr "Anziegen"
```suggestion
msgstr "Anzeigen"
```

2022-11-08 08:31 UTC, jensens commented on plone/app/locales/locales/de/LC_MESSAGES/plone.po
> +msgstr "Seitenfavicon"
```suggestion
msgstr "Seiten-Favicon"
```

2022-11-08 08:31 UTC, jensens commented on plone/app/locales/locales/de/LC_MESSAGES/plone.po
> +msgstr "Desings CSS und JavaScript"
```suggestion
msgstr "CSS und JavaScript des Designs"
```

2022-11-08 08:31 UTC, jensens commented on plone/app/locales/locales/de/LC_MESSAGES/plone.po
> +msgstr "Sperrung aufheben"
Das ist keine Sperrung. Das ist "Unpinning" eines Menues.
```suggestion
msgstr "Abkoppeln"
```

2022-11-08 08:31 UTC, jensens commented on plone/app/locales/locales/de/LC_MESSAGES/plone.po
> +msgstr "Benutzerdaten"
```suggestion
msgstr "Details des Benutzers"
```

2022-11-08 08:31 UTC, jensens commented on plone/app/locales/locales/de/LC_MESSAGES/plone.po
> +msgstr "Sie sind jetz ausgeloggt"
```suggestion
msgstr "Sie sind jetzt abgemeldet."
```

2022-11-08 08:31 UTC, jensens commented on plone/app/locales/locales/de/LC_MESSAGES/plone.po
> +msgstr "Mit dem Upgrade fortfahren"
```suggestion
msgstr "Mit der Aktualisierung fortfahren"
```

2022-11-08 08:31 UTC, jensens commented on plone/app/locales/locales/de/LC_MESSAGES/plone.po
> +msgstr "Dimension"
```suggestion
msgstr "Abmessungen"
```

2022-11-08 08:31 UTC, jensens commented on plone/app/locales/locales/de/LC_MESSAGES/plone.po
> +msgstr "Asynchrone"
```suggestion
msgstr "Async"
```
Dies ist ein Eigenbegriff, der den technischen Attributwert  direct spiegelt und wird nicht übersetzt.

2022-11-08 08:31 UTC, jensens commented on plone/app/locales/locales/de/LC_MESSAGES/plone.po
> +msgstr "Zurückstellen"
```suggestion
msgstr "Defer"
```
Dies ist ein Eigenbegriff, der den technischen Attributwert direct spiegelt und wird nicht übersetzt.

2022-11-08 08:31 UTC, jensens commented on plone/app/locales/locales/de/LC_MESSAGES/widgets.po
> +msgstr "Infos"
```suggestion
msgstr "Informationen"
```
(es gibt keine Infos, das ist Umgangssprachlich)

2022-11-08 08:31 UTC, jensens commented on plone/app/locales/locales/de/LC_MESSAGES/widgets.po
> +msgstr "Vorshaubild"
```suggestion
msgstr "Vorschaubild"
```

2022-11-08 08:32 UTC, jensens commented
@Arhell please only approve if you are really sure everything is fine.

2022-11-09 10:04 UTC, jensens approved these changes

2022-11-09 10:04 UTC, merged