Improve German translations for redirection control panel
collective/plone.app.locales pull request #461
Opened 2024-12-05 20:44 UTC by tisto

2024-12-06 10:55 UTC, jensens requested changes
Kleinigkeiten.

2024-12-06 10:55 UTC, jensens commented on plone/app/locales/locales/de/LC_MESSAGES/plone.po
> +msgstr "Für diesen Inhaltstyp gibt es keinen Arbeitsablauf. Die Sichtbarkeit von Inhalten wird durch das Inhaltsobjekt bestimmt, in denen sich das Objekt befinden."
```suggestion
msgstr "Für diesen Inhaltstyp gibt es keinen Arbeitsablauf. Die Sichtbarkeit von Inhalten wird durch das Inhaltsobjekt bestimmt, in denen sich das Objekt befindet."
```

2024-12-06 10:55 UTC, jensens commented on plone/app/locales/locales/de/LC_MESSAGES/plone.po
> +msgstr "Geben Sie den absoluten Pfad des Ziels an. Der Pfad muss mit '/' beginnen. Das Ziel muss existieren oder auf eine existierende Alternative URL verweisen."
```suggestion
msgstr "Geben Sie den absoluten Pfad des Ziels an. Der Pfad muss mit '/' beginnen. Das Ziel muss existieren oder auf eine existierende alternative URL verweisen."
```

2024-12-09 17:28 UTC, davisagli commented on plone/app/locales/locales/de/LC_MESSAGES/plone.po
> +msgstr "Geben Sie den absoluten Pfad des Ziels an. Der Pfad muss mit '/' beginnen. Das Ziel muss existieren oder auf eine existierende alternative URL verweisen."
```suggestion
msgstr "Geben Sie den absoluten Pfad des Ziels an. Das Ziel muss existieren oder auf eine existierende alternative URL verweisen."
```

2024-12-09 17:29 UTC, davisagli approved these changes

2024-12-09 17:30 UTC, merged